import os.path

from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import FileResponse

from functions.apiwrapper import api_key_auth

router = APIRouter()


@router.get("/getcitiesinstate", dependencies=[Depends(api_key_auth)])
async def get_states(country: str, state: str):
    country_list = ['afghanistan',
                    'albania',
                    'algeria',
                    'andorra',
                    'angola',
                    'antigua and barbuda',
                    'argentina',
                    'armenia',
                    'australia',
                    'austria',
                    'azerbaijan',
                    'bahrain',
                    'bangladesh',
                    'barbados',
                    'belarus',
                    'belgium',
                    'belize',
                    'benin',
                    'bermuda',
                    'bhutan',
                    'bolivia',
                    'bonaire, sint eustatius and saba',
                    'bosnia and herzegovina',
                    'botswana',
                    'brazil',
                    'brunei',
                    'bulgaria',
                    'burkina faso',
                    'burundi',
                    'cambodia',
                    'cameroon',
                    'canada',
                    'cape verde',
                    'central african republic',
                    'chad',
                    'chile',
                    'china',
                    'colombia',
                    'comoros',
                    'congo',
                    'costa rica',
                    "cote d'ivoire (ivory coast)",
                    'croatia',
                    'cuba',
                    'cyprus',
                    'czech republic',
                    'democratic republic of the congo',
                    'denmark',
                    'djibouti',
                    'dominica',
                    'dominican republic',
                    'east timor',
                    'ecuador',
                    'egypt',
                    'el salvador',
                    'equatorial guinea',
                    'eritrea',
                    'estonia',
                    'ethiopia',
                    'fiji islands',
                    'finland',
                    'france',
                    'gabon',
                    'gambia the',
                    'georgia',
                    'germany',
                    'ghana',
                    'greece',
                    'grenada',
                    'guatemala',
                    'guinea',
                    'guinea-bissau',
                    'guyana',
                    'haiti',
                    'honduras',
                    'hong kong s.a.r.',
                    'hungary',
                    'iceland',
                    'india',
                    'indonesia',
                    'iran',
                    'iraq',
                    'ireland',
                    'israel',
                    'italy',
                    'jamaica',
                    'japan',
                    'jordan',
                    'kazakhstan',
                    'kenya',
                    'kiribati',
                    'kosovo',
                    'kuwait',
                    'kyrgyzstan',
                    'laos',
                    'latvia',
                    'lebanon',
                    'lesotho',
                    'liberia',
                    'libya',
                    'liechtenstein',
                    'lithuania',
                    'luxembourg',
                    'madagascar',
                    'malawi',
                    'malaysia',
                    'maldives',
                    'mali',
                    'malta',
                    'marshall islands',
                    'mauritania',
                    'mauritius',
                    'mexico',
                    'micronesia',
                    'moldova',
                    'monaco',
                    'mongolia',
                    'montenegro',
                    'morocco',
                    'mozambique',
                    'myanmar',
                    'namibia',
                    'nauru',
                    'nepal',
                    'netherlands',
                    'new caledonia',
                    'new zealand',
                    'nicaragua',
                    'niger',
                    'nigeria',
                    'north korea',
                    'north macedonia',
                    'norway',
                    'oman',
                    'pakistan',
                    'palau',
                    'palestinian territory occupied',
                    'panama',
                    'papua new guinea',
                    'paraguay',
                    'peru',
                    'philippines',
                    'poland',
                    'portugal',
                    'puerto rico',
                    'qatar',
                    'romania',
                    'russia',
                    'rwanda',
                    'saint kitts and nevis',
                    'saint lucia',
                    'saint vincent and the grenadines',
                    'samoa',
                    'san marino',
                    'sao tome and principe',
                    'saudi arabia',
                    'senegal',
                    'serbia',
                    'seychelles',
                    'sierra leone',
                    'singapore',
                    'slovakia',
                    'slovenia',
                    'solomon islands',
                    'somalia',
                    'south africa',
                    'south korea',
                    'south sudan',
                    'spain',
                    'sri lanka',
                    'sudan',
                    'suriname',
                    'swaziland',
                    'sweden',
                    'switzerland',
                    'syria',
                    'taiwan',
                    'tajikistan',
                    'tanzania',
                    'thailand',
                    'the bahamas',
                    'togo',
                    'tonga',
                    'trinidad and tobago',
                    'tunisia',
                    'turkey',
                    'turkmenistan',
                    'tuvalu',
                    'uganda',
                    'ukraine',
                    'united arab emirates',
                    'united kingdom',
                    'united states',
                    'united states minor outlying islands',
                    'uruguay',
                    'uzbekistan',
                    'vanuatu',
                    'venezuela',
                    'vietnam',
                    'virgin islands (us)',
                    'yemen',
                    'zambia',
                    'zimbabwe']
    if country.lower() in country_list:
        # Sanitise state
        state = sanitise(state)
        if os.path.exists(f"assets/cities/{country.lower()}/{state}.json"):
            return FileResponse(f'assets/cities/{country.lower()}/{state}.json', media_type='application/json')
        else:
            raise HTTPException(status_code=422, detail="State not found")
    else:
        raise HTTPException(status_code=422, detail="Country not found")


def sanitise(state):
    state = state.lower()
    state = state.replace("'", "").replace(".", "").replace("-", "").replace("(", "").replace(")", "").replace("/", "")
    return state
